# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3621f47a8a409d83b3eb47d04f0b1b9ae27f4f0f288d8df3ba13543d40a6723ae11e6b38dba832456be73ac245658b81432d369c24bda36c8685f5abbcff8671

test:
  secret_key_base: 072c8a5fa9ddf8187d5cf3e6915bb01d8b075a3970fe9663e1dbdfade1d06fdb9c7e247103d81fe5864e1a2683bf9cdc2829895b410b1242b5c98dfcbb683ae2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
